In [14]:
from numpy import exp, array, random, dot

In [15]:
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])

In [16]:
training_set_outputs = array([[0, 1, 1, 0]]).T

In [17]:
random.seed(1)

In [18]:
synaptic_weights = 2 * random.random((3, 1)) - 1

In [19]:
synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [20]:
for iter in xrange(10000):
    output = 1. / (1 + exp(-(dot(training_set_inputs, synaptic_weights))))
    synaptic_weights += dot(training_set_inputs.T, (training_set_outputs - output) * output * (1 - output))

In [21]:
print 1 / (1 + exp(-(dot(array([1, 0, 0]), synaptic_weights))))

[ 0.99993704]


In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))


Hello, TensorFlow!


In [9]:
from numpy import exp, array, random, dot


class NeuronLayer():
	"""docstring for NeuronLayer"""
	def __init__(self, number_of_neurons, number_of_inputs_per_neuron):
		self.synaptic_weights = 2 * random.random((number_of_inputs_per_neuron, number_of_neurons)) - 1
		

class NeuralNetwork():
	"""docstring for NeuralNetwork"""
	def __init__(self, layer1, layer2):
		self.layer1 = layer1
		self.layer2 = layer2
		


	def __sigmoid(self, x):
		return 1 / (1 + exp(-x))

	def __sigmoid_derivative(self, x):
		return x * (1 - x)

	def train(self, training_set_inputs, training_set_outputs, num_iter):
		for i in xrange(num_iter):

			output_from_layer1, output_from_layer2 = self.think(training_set_inputs)

			layer2_error = training_set_outputs - output_from_layer2
			layer2_delta = layer2_error * self.__sigmoid_derivative(output_from_layer2)

			layer1_error = layer2_delta.dot(self.layer2.synaptic_weights.T)
			layer1_delta = layer1_error * self.__sigmoid_derivative(output_from_layer1)

			layer1_adjustment = training_set_inputs.T.dot(layer1_delta)
			layer2_adjustment = output_from_layer1.T.dot(layer2_delta)

			self.layer1.synaptic_weights += layer1_adjustment
			self.layer2.synaptic_weights += layer2_adjustment

	def think(self, inputs):
		output_from_layer1 = self.__sigmoid(dot(inputs, self.layer1.synaptic_weights))
		output_from_layer2 = self.__sigmoid(dot(output_from_layer1, self.layer2.synaptic_weights))

		return output_from_layer1, output_from_layer2

	def print_weights(self):
		print "    Layer 1 (4 neurons, each with 3 inputs): "
		print self.layer1.synaptic_weights
		print "    Layer 2 (1 neuron, with 4 inputs):"
		print self.layer2.synaptic_weights

if __name__ == '__main__':

	random.seed(1)

	layer1 = NeuronLayer(4, 3)
	layer2 = NeuronLayer(1, 4)

	neural_network = NeuralNetwork(layer1, layer2)

	print "Stage 1) Random starting synaptic weights: "
	neural_network.print_weights()


	training_set_inputs = array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1], [0, 0, 0]])
	training_set_outputs = array([[0, 1, 1, 1, 1, 0, 0]]).T


	neural_network.train(training_set_inputs, training_set_outputs, 60000)
	print "Stage 2) New synaptic weights after training: "
	print neural_network.print_weights()

	# Test the neural network with a new situation.
	print "Considering new situation [1, 1, 0] -> ?: "
	hidden_state, output =  neural_network.think(array([1, 1, 0]))
	print output



Stage 1) Random starting synaptic weights: 
    Layer 1 (4 neurons, each with 3 inputs): 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
    Layer 2 (1 neuron, with 4 inputs):
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
Stage 2) New synaptic weights after training: 
    Layer 1 (4 neurons, each with 3 inputs): 
[[ 0.3122465   4.57704063 -6.15329916 -8.75834924]
 [ 0.19676933 -8.74975548 -6.1638187   4.40720501]
 [-0.03327074 -0.58272995  0.08319184 -0.39787635]]
    Layer 2 (1 neuron, with 4 inputs):
[[ -8.18850925]
 [ 10.13210706]
 [-21.33532796]
 [  9.90935111]]
None
Considering new situation [1, 1, 0] -> ?: 
[ 0.0078876]
